name: Deploy-workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: install node js
        uses: actions/setup-node@v4

      - name: setup project
        run: make setup

      - name: run tests
        run: make test

      - name: run lint
        run: make lint
