name: Deploy-workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        cloneRepository: actions/checkout@v4
        usesInstallNodeJS: actions/setup-node@v4

      - name: setup project
        run: make setup

      - name: run tests
        run: make test

      - name: run lint
        run: make lint
