name: Deploy-workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: make setup

      - name: run tests
        run: make test

      - name: run lint
        run: make lint
